"""Markdown rendering for the suspect-ranking report (§5.6)."""

from __future__ import annotations


def format_distance(distance: object) -> str:
    """Render a BFS distance, showing unreachable nodes as 'inf'."""
    return "inf" if distance is None else str(distance)


def build_markdown(rows: list[dict[str, object]], seed_label: str, top: int) -> str:
    """Build the Markdown report string."""
    lines: list[str] = []
    lines.append("# Suspect Ranking Report")
    lines.append("")
    lines.append(
        "This report ranks graph nodes as bug **suspects** for a graph-guided "
        "debugging workflow. It is generated by `agent/rank_suspects.py` from "
        "`data/graph.json` (assignment extension, §5.6)."
    )
    lines.append("")
    lines.append("## Method")
    lines.append("")
    lines.append(
        "Each node is scored by combining two signals computed over the "
        "**undirected** version of the graph:"
    )
    lines.append("")
    lines.append(
        "- **Degree centrality** = `degree / (n_nodes - 1)` — how connected the "
        "node is (wide blast radius if buggy)."
    )
    lines.append(
        "- **Proximity to the seed** = `1 / (1 + distance_to_seed)`, where "
        "`distance_to_seed` is the BFS shortest-path distance (in hops) from the "
        "seed node. Unreachable nodes have distance `inf` and proximity `0`."
    )
    lines.append("")
    lines.append("The combined **suspect score** is:")
    lines.append("")
    lines.append("```")
    lines.append("score = degree_centrality + 1 / (1 + distance_to_seed)")
    lines.append("```")
    lines.append("")
    lines.append(
        "This rewards nodes that are both well-connected and close to the seed, "
        "so the seed itself and its well-connected neighbours rank highest — "
        "telling the agent which nodes to inspect first."
    )
    lines.append("")
    lines.append(f"**Seed node:** `{seed_label}`")
    lines.append("")
    lines.append(f"## Top {top} suspects")
    lines.append("")
    lines.append(
        "| Rank | Node | Degree | Degree centrality | Distance to seed | Suspect score |"
    )
    lines.append(
        "| ---: | --- | ---: | ---: | ---: | ---: |"
    )
    for rank, row in enumerate(rows[:top], start=1):
        lines.append(
            "| {rank} | `{label}` | {degree} | {dc:.3f} | {dist} | {score:.3f} |".format(
                rank=rank,
                label=row["label"],
                degree=row["degree"],
                dc=row["degree_centrality"],
                dist=format_distance(row["distance"]),
                score=row["score"],
            )
        )
    lines.append("")
    return "\n".join(lines)
